### PR TITLE
Separate splitters into a layer.

### PR DESCRIPTION
**Pull request by junsikshim**
Related issue: #11 

I've separated splitters into a new layer(`SplitterLayer`), and it's on the same level as `PaneRows`.
Splitters are managed in `SplitterRegistry`, and all the splitter-related files are located in `splitter` directory.

`SplitterIntersectionHandle` is a square `div` which acts as a handle to move two splitters at the same time.
There is a bug in which horizontal splitter's width does not keep up with the pointer movement. Let's move that into a separate issue.

Also, I've refactored `PaneSystem` and `PaneRow` to reduce the number of unnecessary props.
(There still exist unused props though)

### CODE REVIEW

**Comment by junsikshim** [comment]
I think this PR is ready with the exception of the bug mentioned above.
Please review this! @hchangjae

**Comment by hchangjae** [comment]
Awesome!

**Comment by hchangjae** [comment]
https://github.com/junsikshim/react-pane-system/assets/52942171/3ff4f402-d6c0-490b-a683-39cd01b3dbae


The bug mentioned above refers to this, right?
I also think it might be better to address this as a separate issue.

**Review by hchangjae — APPROVED** [review]

**Comment by junsikshim** [comment]
> The bug mentioned above refers to this, right? I also think it might be better to address this as a separate issue.

Yeah, I'll merge this, and create a new issue regarding the bug.

**Pull request merged**
